### ISSUE TITLE
Consider non-osx support

### ISSUE THREAD

**Issue by subsidel** [AlexChesters/redrand#2]
For example xdg-open for other *nix's that have it

https://wiki.archlinux.org/index.php/xdg-open

**Comment by AlexChesters** [comment]
I'm only really familiar with OS X. What are you opinions on the following?

```
OS="$(uname)"
if [ "$OS" == "Darwin" ]; then
    OPEN_COMMAND=open
else
    OPEN_COMMAND=xdg-open
fi
```

I think it's a tad ugly, but I'm unsure of any other way.

**Comment by AlexChesters** [comment]
Fixed in #6

**Comment by subsidel** [comment]
¯\_(ツ)_/¯ It worked so why not

**Comment by AlexChesters** [comment]
:+1:
